---
- name: Generate Sanoid Configuration
  template:
    src: sanoid.conf.j2
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: 0644

- name: Create Sanoid Log
  file:
    path: "{{ item }}"
    state: touch
    owner: root
    group: root
    mode: 0644
  with_items:
    - /var/log/sanoid-cron.log
